name: DJ MARK CHAI
favicon: null
layout_spectrum: 0.3133289834950119
typography_spectrum: 0.425409275572747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4175476070959121
  lightness: 0.8545099073089659
  saturation: 0.5309873290825635
  rhythmicContrast: 0.750684987520799
purpose: []
