name: DJ MARK CHAI
favicon: null
layout_spectrum: 0.69772
typography_spectrum: 0.50867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89819c'
    - '#ffffff'
    - '#12110c'
    - '#b6be74'
    - '#874e55'
  brandStrength: 0.375
  lightness: 0.8545099073089659
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
